test:
  stage: test
  image:
    name: docker:20
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""
  services:
    - name: docker:20-dind
      alias: docker
      command: ["--tls=false"]
  script:
    - docker compose up -d --remove-orphans --wait traefik whoami
    - docker compose run test

