displayName: Rate Limit
type: middleware
import: gitlab-private.wildberries.ru/wbpay-go/traefik-ratelimit
summary: Rate Limit
testData:
  keeperRateLimitKey: wbpay-ratelimits
  keeperURL: http://keepedev:8080
  keeperAdminPassword: Pa$sw0rd
  keeperReqTimeout: 300s
